### ISSUE TITLE
Optimize the HTML and whatnot so that bigger pages can get past Cloudflare.

### ISSUE THREAD

**Issue by IoIxD** [IoIxD/DFS#51]
We now host a post that has nearly 3000 messages.
It's actually only 3 megabytes but 56mb worth of resources is transferred and CloudFlare refuses to send this to the user.

We need to look into optimization of resources sent in order to have larger posts like this sent.

[The post in question](https://dfs.ioi-xd.net/662191386942111744/1019811690042368060/1023640405067177984)

**Comment by samhza** [comment]
Issue with Cloudflare serving that post has to do with timeouts not size

**Comment by IoIxD** [comment]
Indeed, I forgot that we hadn't pushed Sam's "message cache" changes
